#!/usr/bin/env bash
# Fix Nginx to run as nginx user on port 8080 in 7 lines or less
sed -i "s/listen 80/listen 8080/g" /etc/nginx/sites-enabled/default
sed -i "s/user .*/user nginx;/" /etc/nginx/nginx.conf
pkill apache2
service nginx restart
su nginx
