#!/usr/bin/env bash
# Fix Nginx to run as nginx user on port 8080 in 7 lines or less
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/g" /etc/nginx/sites-available/default
pkill apache2
service nginx stop
service nginx start
