#!/usr/bin/env bash
# Fix Nginx to run as nginx user on port 8080 in 7 lines or less
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -s /bin/bash -c 'service nginx start'
