#!/usr/bin/env bash
# Install and configure HAProxy load balancer

# Update and install HAProxy
apt-get update
apt-get install -y haproxy

# Enable HAProxy to start via init script
echo "ENABLED=1" > /etc/default/haproxy

# Backup original config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6787-web-01 98.93.145.166:80 check
    server 6787-web-02 18.208.133.10:80 check
EOF

# Restart HAProxy
service haproxy restart
