#!/usr/bin/env bash
# Script that installs and configures Nginx on web-01 server

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create custom index page with "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Start nginx service (without using systemctl)
service nginx start
