#!/usr/bin/env bash
# Script that configures Nginx server with a custom 404 page

apt-get update -y
apt-get install nginx -y

# Create main page
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure redirect
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

# Configure custom 404 page
sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n' /etc/nginx/sites-available/default

service nginx restart
