#!/usr/bin/env bash
# Script that configures Nginx with a custom 404 page

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create custom index page
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure redirect for /redirect_me
sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Configure custom 404 page
sed -i '/server_name _;/a \    error_page 404 /404.html;\n    location = /404.html {\n        internal;\n    }' /etc/nginx/sites-available/default

# Start nginx service
service nginx start
